name: Lab2 pipeline


on:
  pull_request:
    branches:
      - develop

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  
          cache: gradle  

      
  

 
      - name: Build the project
        run: ./gradlew build --no-daemon 


      - name: Run tests
        run: ./gradlew test --no-daemon --rerun-tasks --warning-mode all