name: Java CI

on:
  push:
    branches: [ feature/lab2 ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        java-version: '23'
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test
 
